# Generated by Django 5.0.6 on 2024-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('body_fat_percentage_reduction', 'Body Fat Percentage Reduction'), ('muscle_gain', 'Muscle Gain'), ('endurance_improvement', 'Endurance Improvement'), ('strength_improvement', 'Strength Improvement'), ('distance_running', 'Distance Running'), ('distance_cycling', 'Distance Cycling'), ('distance_swimming', 'Distance Swimming'), ('number_of_workouts_per_week', 'Number of Workouts per Week'), ('number_of_steps_per_day', 'Number of Steps per Day'), ('calorie_intake_reduction', 'Calorie Intake Reduction'), ('calorie_intake_increase', 'Calorie Intake Increase')], max_length=255),
        ),
    ]
